[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "panther"
version = "0.0.1"
description = "Panther by Mahmood Lab"
readme = "README.md"
authors = [
    {name = "Paul Huettl"},
    {name = "Lukas Wolfseher"},
]